SELECT * FROM RESERVATION;

ALTER TABLE RESERVATION 
RENAME COLUMN RESERV_NUMBER TO RESERV_COUNT;

-- ALTER TABLE 테이블명 ADD(컬럼명 데이터타입 [DEFAULT '값']);
ALTER TABLE RESERVATION ADD (RESERV_REQUEST NVARCHAR2(1000));

SELECT * FROM "STORE";

INSERT INTO "STORE" VALUES(
	SEQ_STORE_NO.NEXTVAL,
	'기와탭룸',
	'삼청동 한옥카페말고 한옥펍에서 즐기는 수제맥주',
	'서울 종로구 율곡로1길 74-7 1층',
	DEFAULT,
	10,
	'02-733-1825',
	'12:00',
	'23:00',
	NULL,
	NULL,		
	DEFAULT,
	'/images/profile/20240503154154_00016.jpg',
	4.42,
	2,
	5
);	

COMMIT;

ROLLBACK;

SELECT * FROM "MEMBER";

SELECT STORE_NO, STORE_NAME, STORE_INFO, STORE_LOCATION, STORE_STATUS, STORE_MAX_NUMBER, STORE_TEL, OPEN_HOUR, CLOSE_HOUR,
				BREAKTIME_START, BREAKTIME_END, STORE_CLOSED, STORE_IMG, TOTAL_RATING, STORE_MAX_TABLE, MEMBER_NO
				
FROM "STORE"
WHERE STORE_NO=1;

SELECT * FROM "RESERVATION";

 