ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER SEMI_LJS IDENTIFIED BY dlwltn;

GRANT CREATE SESSION TO SEMI_LJS;

GRANT CREATE TABLE TO SEMI_LJS;

ALTER USER SEMI_LJS
DEFAULT TABLESPACE USERS
QUOTA 10M ON USERS;

SELECT * FROM ROLE_SYS_PRIVS
WHERE ROLE = 'RESOURCE';

GRANT CONNECT, RESOURCE TO SEMI_LJS;

---------------------------------------
-- final 백업용 계정
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER JISOO IDENTIFIED BY JISOO1234;

GRANT CREATE SESSION TO JISOO;

GRANT CREATE TABLE TO JISOO;

ALTER USER JISOO
DEFAULT TABLESPACE USERS
QUOTA 10M ON USERS;

SELECT * FROM ROLE_SYS_PRIVS
WHERE ROLE = 'RESOURCE';

GRANT CONNECT, RESOURCE TO JISOO;

---------------------------------------
-- semi 백업용 계정
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER SEMI_BACKUP IDENTIFIED BY BACKUP1234;

GRANT CREATE SESSION TO SEMI_BACKUP;

GRANT CREATE TABLE TO SEMI_BACKUP;

ALTER USER SEMI_BACKUP
DEFAULT TABLESPACE USERS
QUOTA 10M ON USERS;

SELECT * FROM ROLE_SYS_PRIVS
WHERE ROLE = 'RESOURCE';

GRANT CONNECT, RESOURCE TO SEMI_BACKUP;

SELECT USERNAME FROM DBA_USERS WHERE USERNAME = 'SPRING_SEMI';