ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER SEMI_LJS IDENTIFIED BY dlwltn;

GRANT CREATE SESSION TO SEMI_LJS;

GRANT CREATE TABLE TO SEMI_LJS;

ALTER USER SEMI_LJS
DEFAULT TABLESPACE USERS
QUOTA 10M ON USERS;

SELECT * FROM ROLE_SYS_PRIVS
WHERE ROLE = 'RESOURCE';

GRANT CONNECT, RESOURCE TO SEMI_LJS;
